apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: nodejs-ci-pipelinerun
spec:
  pipelineRef:
    name: nodejs-ci-pipeline
  params:
    - name: repo-url
      value: https://github.com/rh-imesquit/nodejs-pipelines-gitops.git
    - name: image-name
      value: nodejs-lab-app
    - name: image_tag
      value: v1.4
    - name: git-username
      value: rh-imesquit
    - name: git-email
      value: imesquit@redhat.com
    - name: git-repo
      value: rh-imesquit/nodejs-pipelines-gitops
    - name: git-branch
      value: main
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: pipeline-pvc
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
  taskRunTemplate:
    podTemplate:
      securityContext:
        fsGroup: 65532