apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: nodejs-tests
spec:
  description: "Run automated tests for Node.js app using Jest"
  workspaces:
    - name: source
      description: Cloned source code from Git repository
  steps:
    - name: run-tests
      image: registry.access.redhat.com/ubi8/nodejs-18
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        echo "[INFO] Installing dependencies..."
        npm install

        echo "[INFO] Running tests..."
        npm test
