apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-lab-app
  labels:
    app: nodejs-lab-app
    version: "v1.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-lab-app
  template:
    metadata:
      labels:
        app: nodejs-lab-app
    spec:
      containers:
        - name: nodejs-lab-app
          image: image-registry.openshift-image-registry.svc:5000/app/nodejs-lab-app:v1.1
          ports:
            - containerPort: 3000
